# Generated by Django 5.1.7 on 2025-03-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("IP", models.BooleanField(default=False)),
                ("HPDF", models.BooleanField(default=False)),
                ("BLK_TOP", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Criteria",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "maturity",
                    models.CharField(
                        choices=[("ML1", "ML1"), ("ML2", "ML2"), ("ML3", "ML3")],
                        default="ML1",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CriterionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_targets",
                        to="modeling.criterion",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="criterion_target_ownerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "execution_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "log_file_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("log_content", models.TextField(blank=True, null=True)),
                (
                    "evaluated_maturity",
                    models.CharField(
                        blank=True,
                        choices=[("ML1", "ML1"), ("ML2", "ML2"), ("ML3", "ML3")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criterion_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="modeling.criteriontarget",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="criteriontarget",
            name="recent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recent_execution",
                to="modeling.execution",
            ),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField()),
                ("branch", models.CharField(max_length=100)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="repositories", to="modeling.project"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IP", "IP"),
                            ("HPDF", "HPDF"),
                            ("BLK_TOP", "BLK_TOP"),
                        ],
                        max_length=10,
                        verbose_name="Block Type",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="modeling.repository",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="criteriontarget",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criterion_targets",
                to="modeling.target",
            ),
        ),
        migrations.AddConstraint(
            model_name="criteriontarget",
            constraint=models.UniqueConstraint(
                fields=("criterion", "target"), name="unique_criterion_target"
            ),
        ),
    ]
