# Generated by Django 5.1.7 on 2025-04-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criterion",
            name="BLK_TOP",
        ),
        migrations.RemoveField(
            model_name="criterion",
            name="HPDF",
        ),
        migrations.RemoveField(
            model_name="criterion",
            name="IP",
        ),
        migrations.RemoveField(
            model_name="target",
            name="type",
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("repository", "name"), name="unique__name__per__repository"
            ),
        ),
    ]
