# Generated by Django 5.1.7 on 2025-04-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0002_remove_criterion_blk_top_remove_criterion_hpdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="is_HPDF",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="is_IP",
            field=models.BooleanField(default=True),
        ),
    ]
