# Generated by Django 5.1.7 on 2025-04-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0003_target_is_hpdf_target_is_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="is_IP",
            field=models.BooleanField(default=False),
        ),
    ]
