# Generated by Django 5.1.7 on 2025-04-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0004_alter_target_is_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
