# Generated by Django 5.1.7 on 2025-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0005_criterion_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="branch",
        ),
        migrations.AddField(
            model_name="execution",
            name="branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="commit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
