# Generated by Django 5.1.7 on 2025-04-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0006_remove_repository_branch_execution_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maturity",
                    models.CharField(
                        blank=True,
                        choices=[("ML1", "ML1"), ("ML2", "ML2"), ("ML3", "ML3")],
                        help_text="비워두면 모든 ML에 공통 적용됨",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("max_error", models.IntegerField(blank=True, null=True)),
                ("allow_warning", models.BooleanField(default=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="modeling.criterion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("criterion", "maturity"),
                        name="unique_criterion_maturity_rule",
                    )
                ],
            },
        ),
    ]
