# Generated by Django 5.1.7 on 2025-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0008_historicalcriterion_historicalcriteriontarget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="available_HPDF",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="available_IP",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcriterion",
            name="available_HPDF",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcriterion",
            name="available_IP",
            field=models.BooleanField(default=True),
        ),
    ]
