# Generated by Django 5.0.6 on 2025-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0011_alter_execution_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="build_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalexecution",
            name="build_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
