# Generated by Django 5.0.6 on 2025-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0012_execution_build_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
