# Generated by Django 5.0.6 on 2025-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0013_alter_execution_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="log_file",
            field=models.FileField(
                blank=True,
                help_text="Path to the log file associated with this execution.",
                null=True,
                upload_to="execution_logs/",
            ),
        ),
        migrations.AddField(
            model_name="historicalexecution",
            name="log_file",
            field=models.TextField(
                blank=True,
                help_text="Path to the log file associated with this execution.",
                max_length=100,
                null=True,
            ),
        ),
    ]
