# Generated by Django 5.0.6 on 2025-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0014_execution_log_file_historicalexecution_log_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                    ("RUNNING", "Running"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                    ("RUNNING", "Running"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
