# Generated by Django 5.0.6 on 2025-06-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0016_evaluationpattern_historicalevaluationpattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationrule",
            name="allow_warning",
        ),
        migrations.RemoveField(
            model_name="evaluationrule",
            name="max_error",
        ),
        migrations.RemoveField(
            model_name="historicalevaluationrule",
            name="allow_warning",
        ),
        migrations.RemoveField(
            model_name="historicalevaluationrule",
            name="max_error",
        ),
        migrations.AddField(
            model_name="evaluationrule",
            name="pattern",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="modeling.evaluationpattern",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluationrule",
            name="ruleset",
            field=models.TextField(default="[0, -1]"),
        ),
        migrations.AddField(
            model_name="historicalevaluationrule",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="modeling.evaluationpattern",
            ),
        ),
        migrations.AddField(
            model_name="historicalevaluationrule",
            name="ruleset",
            field=models.TextField(default="[0, -1]"),
        ),
    ]
