# Generated by Django 5.0.6 on 2025-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0017_remove_evaluationrule_allow_warning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationrule",
            name="ruleset",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="historicalevaluationrule",
            name="ruleset",
            field=models.TextField(),
        ),
    ]
