# Generated by Django 5.0.6 on 2025-06-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0018_alter_evaluationrule_ruleset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                    ("RUNNING", "Running"),
                    ("WAITING", "WAITING"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("DM Not Ready", "DM Not Ready"),
                    ("EXEC Not Ready", "EXEC Not Ready"),
                    ("UNVERIFIED", "UNVERIFIED"),
                    ("RUNNING", "Running"),
                    ("WAITING", "WAITING"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
