# Generated by Django 5.0.6 on 2025-06-30 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0019_alter_execution_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(fields=["status"], name="modeling_ex_status_13ffcf_idx"),
        ),
    ]
