# Generated by Django 5.0.6 on 2025-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0020_execution_modeling_ex_status_13ffcf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='available_DFTed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcriterion',
            name='available_DFTed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltarget',
            name='is_DFTed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='is_DFTed',
            field=models.BooleanField(default=False),
        ),
    ]
