# Generated by Django 5.0.6 on 2025-08-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0022_populate_dfted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workflow_type',
            field=models.CharField(choices=[('IP', 'IP'), ('HPDF', 'HPDF'), ('DFTed', 'DFTed')], default='IP', help_text='The workflow type for this execution (IP, HPDF, or DFTed)', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='workflow_type',
            field=models.CharField(choices=[('IP', 'IP'), ('HPDF', 'HPDF'), ('DFTed', 'DFTed')], default='IP', help_text='The workflow type for this execution (IP, HPDF, or DFTed)', max_length=10),
        ),
    ]
