# Generated by Django 5.0.6 on 2025-08-12 09:28

from django.db import migrations


def populate_execution_workflow_type(apps, schema_editor):
    """
    Populate workflow_type for existing executions based on target type.
    Since DFTed wasn't used yet, we only need to distinguish IP vs HPDF.
    """
    Execution = apps.get_model('modeling', 'Execution')
    
    ip_count = 0
    hpdf_count = 0
    
    for execution in Execution.objects.all():
        target = execution.criterion_target.target
        
        if target.is_IP:
            execution.workflow_type = "IP"
            ip_count += 1
        elif target.is_HPDF:
            execution.workflow_type = "HPDF"
            hpdf_count += 1
        else:
            # Fallback (shouldn't happen with current data)
            execution.workflow_type = "IP"
            ip_count += 1
            
        execution.save()
    
    print(f"Updated workflow_type: {ip_count} IP executions, {hpdf_count} HPDF executions")


def reverse_execution_workflow_type(apps, schema_editor):
    """
    Reverse migration - reset workflow_type to default
    """
    Execution = apps.get_model('modeling', 'Execution')
    Execution.objects.all().update(workflow_type="IP")


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0023_add_workflow_type_to_execution'),
    ]

    operations = [
        migrations.RunPython(
            populate_execution_workflow_type,
            reverse_execution_workflow_type,
        ),
    ]
