# Generated by Django 5.0.6 on 2025-08-13 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0024_populate_execution_workflow_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='execution',
            new_name='exec_status_idx',
            old_name='modeling_ex_status_13ffcf_idx',
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['available_IP'], name='crit_avail_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['available_HPDF'], name='crit_avail_hpdf_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['available_DFTed'], name='crit_avail_dfted_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['name'], name='crit_name_idx'),
        ),
        migrations.AddIndex(
            model_name='criteriontarget',
            index=models.Index(fields=['criterion', 'target'], name='ct_crit_tgt_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['workflow_type'], name='exec_wf_type_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['branch'], name='exec_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['executed_at'], name='exec_date_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['criterion_target', 'workflow_type', '-executed_at'], name='exec_ct_wf_date_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['workflow_type', 'branch', '-executed_at'], name='exec_wf_br_date_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['criterion_target', 'workflow_type', 'branch', '-executed_at'], name='exec_ct_wf_br_date_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['criterion_target', '-executed_at'], name='exec_ct_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['is_IP'], name='tgt_is_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['is_HPDF'], name='tgt_is_hpdf_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['is_DFTed'], name='tgt_is_dfted_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['repository', 'is_IP'], name='tgt_repo_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['repository', 'is_HPDF'], name='tgt_repo_hpdf_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['repository', 'is_DFTed'], name='tgt_repo_dfted_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['name'], name='tgt_name_idx'),
        ),
    ]
