# Generated by Django 5.0.6 on 2025-08-13 05:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0025_rename_modeling_ex_status_13ffcf_idx_exec_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCriteriaGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for the group (e.g., #007bff)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of groups (lower numbers appear first)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Criteria Group',
                'verbose_name_plural': 'historical Criteria Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['group__order', 'order_in_group', 'name'], 'verbose_name_plural': 'Criteria'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='order_in_group',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the group (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='historicalcriterion',
            name='order_in_group',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the group (lower numbers appear first)'),
        ),
        migrations.CreateModel(
            name='CriteriaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for the group (e.g., #007bff)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of groups (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Criteria Group',
                'verbose_name_plural': 'Criteria Groups',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['order'], name='cgrp_order_idx'), models.Index(fields=['name'], name='cgrp_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this criterion belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria', to='modeling.criteriagroup'),
        ),
        migrations.AddField(
            model_name='historicalcriterion',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Group this criterion belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='modeling.criteriagroup'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['group'], name='crit_group_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['order_in_group'], name='crit_order_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['group', 'order_in_group'], name='crit_grp_order_idx'),
        ),
        migrations.AddField(
            model_name='historicalcriteriagroup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
