# Generated by Django 5.0.6 on 2025-08-22 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0027_executionbatch_execution_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
