# Generated by Django 5.0.6 on 2025-08-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0028_execution_updated_at_historicalexecution_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='display_type',
            field=models.CharField(choices=[('success_fail', 'Success/Fail'), ('numeric_value', 'Numeric Value')], default='success_fail', help_text='How this criterion should be displayed in the UI', max_length=20),
        ),
        migrations.AddField(
            model_name='execution',
            name='display_value',
            field=models.CharField(blank=True, help_text='Value to display in UI based on criterion display_type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcriterion',
            name='display_type',
            field=models.CharField(choices=[('success_fail', 'Success/Fail'), ('numeric_value', 'Numeric Value')], default='success_fail', help_text='How this criterion should be displayed in the UI', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalexecution',
            name='display_value',
            field=models.CharField(blank=True, help_text='Value to display in UI based on criterion display_type', max_length=100, null=True),
        ),
    ]
