# Generated by Django 5.0.6 on 2025-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0029_add_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit for numeric display values (e.g., 'um²', 'ns', 'gates')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcriterion',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit for numeric display values (e.g., 'um²', 'ns', 'gates')", max_length=20, null=True),
        ),
    ]
